export * from './catalogue';
export * from "./hotel";
export * from './speciality'
export * from "./carousels";
export * from "./location";
export * from "./country";
export * from "./wilaya";
export * from "./map";
export * from "./univ";
export * from "./agency";
export * from "./creche";